# Backtracking Sudoku Solver 

A sudoku solver which finds the solution using backtracking, a brute force search method which utilises depth first search. 

Below is an example sudoku puzzle with its corresponing solution. To find a solution the algorithm places the lowest legal number in the first empty space of the top row, 1 in this case. Next it looks at the second empty space, repeating this process it places 2. The algorithm repeats this process until it finds a solution or an empty space with no possible value. In this example this occurs at the last empty space on the first row (shown by the red X). At which point the algorithm *backtracks* to the last space with multiple options, the space with the blue 8 in this case and tries with the next legal value, which is 9 here. This is repeated until a solution is found or all posible values are tried. 

The completed sudoku is shown in the third image.

<img src="images/Sudoku_unsolved.png" style="width: 200px;"/>
<img src="images/Sudoku_partsolved.png" style="width: 200px;"/>
<img src="images/Sudoku_solved.png" style="width: 200px;"/>

In [1]:
import numpy as np

# Load sudokus
sudokus = np.load("data/sudokus.npy")
print("Shape of one sudoku array:", sudokus[0].shape, ". Type of array values:", sudokus.dtype)

# Load solutions
solutions = np.load("data/sudoku_solutions.npy")
print("Shape of one sudoku solution array:", solutions[0].shape, ". Type of array values:", solutions.dtype, "\n")

# Print the first sudoku...
print("Sudoku #1:")
print(sudokus[0], "\n")

# ...and its solution
print("Solution of Sudoku #1:")
print(solutions[0])

Shape of one sudoku array: (9, 9) . Type of array values: float64
Shape of one sudoku solution array: (9, 9) . Type of array values: float64 

Sudoku #1:
[[0. 0. 4. 0. 8. 3. 0. 0. 2.]
 [0. 5. 1. 0. 0. 4. 3. 0. 0.]
 [0. 0. 0. 0. 9. 6. 7. 1. 0.]
 [1. 2. 0. 8. 0. 0. 0. 0. 6.]
 [0. 4. 0. 0. 0. 0. 5. 0. 0.]
 [8. 3. 0. 6. 0. 7. 9. 0. 0.]
 [0. 6. 0. 3. 0. 9. 0. 4. 0.]
 [0. 0. 7. 0. 0. 0. 2. 0. 5.]
 [0. 9. 0. 0. 5. 0. 8. 0. 3.]] 

Solution of Sudoku #1:
[[9. 7. 4. 1. 8. 3. 6. 5. 2.]
 [6. 5. 1. 2. 7. 4. 3. 8. 9.]
 [2. 8. 3. 5. 9. 6. 7. 1. 4.]
 [1. 2. 9. 8. 3. 5. 4. 7. 6.]
 [7. 4. 6. 9. 1. 2. 5. 3. 8.]
 [8. 3. 5. 6. 4. 7. 9. 2. 1.]
 [5. 6. 8. 3. 2. 9. 1. 4. 7.]
 [3. 1. 7. 4. 6. 8. 2. 9. 5.]
 [4. 9. 2. 7. 5. 1. 8. 6. 3.]]


In [2]:
def sudoku_solver(sudoku):
    """
    Solves a Sudoku puzzle and returns its unique solution.

        Args:
            sudoku: 9x9 numpy array, empty cells are designated by 0.

        Returns
            solution: 9x9 numpy array of integers. 
                      It contains the solution, if there is one. 
                      If there is no solution, all array entries should be -1.
    """
    #pass sudoku to recurrsive function to perform backtracking and return sudoku if solution is found
    if sudoku_solver_rec(sudoku):
        return sudoku
    #return array of -1's if no solution is found
    else:
        return np.zeros((9,9))-1

def sudoku_solver_rec(sudoku): 
  
    #Check if any cell is unassigned i.e is 0
    for row in range(0,9):
        for column in range(0,9):
            if sudoku[row][column] == 0:
                for i in range(1,10): 
                    #Check if value satisfies constraints  
                    if(no_conflict(i,row,column,sudoku)): 
                        #assign value then perform recurrsion  
                        sudoku[row][column] = i 
                        
                        #return true if solution found 
                        if(sudoku_solver_rec(sudoku)): 
                            return True
  
                        #unassign value if not the solution 
                        sudoku[row][column] = 0
              
                #backtrack if no value satisfies constraints       
                return False 
    #return true if sudoku is solved i.e. no cell is 0
    return True

def no_conflict(i,row,column,sudoku): 
    #return True if i is not in the corresponding row, column or 3x3 square
    return not i in sudoku[row] and not i in sudoku[:,column] and not_in3x3(i, row, column, sudoku)

def not_in3x3(i,row,column,sudoku):
    #returns true if i is not in the corresponding 3x3 square and false if row or column are out of range
    if 0 <= row < 3:
        if 0 <= column < 3:
            return i not in sudoku[0:3,0:3]
        if column < 6:
            return i not in sudoku[0:3,3:6]
        if column < 9:
            return i not in sudoku[0:3,6:9]
    if row < 6:
        if 0 <= column < 3:
            return i not in sudoku[3:6,0:3]
        if column < 6:
            return i not in sudoku[3:6,3:6]
        if column < 9:
            return i not in sudoku[3:6,6:9]
    if row < 9:
        if 0 <= column < 3:
            return i not in sudoku[6:9,0:3]
        if column < 6:
            return i not in sudoku[6:9,3:6]
        if column < 9:
            return i not in sudoku[6:9,6:9]
    else:
        return False

In [3]:
# Test algorithm on example sudokus

for i in range(len(sudokus)):
    sudoku = sudokus[i].copy()
    print("This is sudoku number", i+1)
    print(sudoku)
    solution = sudoku_solver(sudokus[i])
    print("The solution for sudoku number", i+1)
    print(solution)
    print("Is the solution correct?")
    print(np.array_equal(solution, solutions[i]))
    print('')


This is sudoku number 1
[[0. 0. 4. 0. 8. 3. 0. 0. 2.]
 [0. 5. 1. 0. 0. 4. 3. 0. 0.]
 [0. 0. 0. 0. 9. 6. 7. 1. 0.]
 [1. 2. 0. 8. 0. 0. 0. 0. 6.]
 [0. 4. 0. 0. 0. 0. 5. 0. 0.]
 [8. 3. 0. 6. 0. 7. 9. 0. 0.]
 [0. 6. 0. 3. 0. 9. 0. 4. 0.]
 [0. 0. 7. 0. 0. 0. 2. 0. 5.]
 [0. 9. 0. 0. 5. 0. 8. 0. 3.]]
The solution for sudoku number 1
[[9. 7. 4. 1. 8. 3. 6. 5. 2.]
 [6. 5. 1. 2. 7. 4. 3. 8. 9.]
 [2. 8. 3. 5. 9. 6. 7. 1. 4.]
 [1. 2. 9. 8. 3. 5. 4. 7. 6.]
 [7. 4. 6. 9. 1. 2. 5. 3. 8.]
 [8. 3. 5. 6. 4. 7. 9. 2. 1.]
 [5. 6. 8. 3. 2. 9. 1. 4. 7.]
 [3. 1. 7. 4. 6. 8. 2. 9. 5.]
 [4. 9. 2. 7. 5. 1. 8. 6. 3.]]
Is the solution correct?
True

This is sudoku number 2
[[0. 0. 0. 0. 6. 0. 2. 8. 0.]
 [7. 0. 9. 0. 0. 1. 0. 0. 0.]
 [8. 6. 0. 3. 2. 0. 0. 7. 4.]
 [9. 0. 0. 0. 4. 0. 5. 1. 0.]
 [0. 0. 7. 1. 9. 0. 3. 4. 0.]
 [0. 0. 3. 0. 0. 6. 0. 0. 2.]
 [0. 0. 2. 9. 7. 0. 0. 0. 0.]
 [3. 0. 0. 8. 0. 0. 9. 0. 5.]
 [5. 0. 0. 0. 0. 0. 0. 2. 1.]]
The solution for sudoku number 2
[[4. 3. 1. 5. 6. 7. 2. 8. 9.]
 [7. 2. 9. 4

The solution for sudoku number 16
[[1. 6. 3. 4. 8. 9. 2. 5. 7.]
 [9. 5. 4. 7. 2. 1. 6. 8. 3.]
 [8. 7. 2. 6. 3. 5. 9. 4. 1.]
 [6. 3. 8. 5. 1. 7. 4. 2. 9.]
 [2. 4. 7. 8. 9. 3. 1. 6. 5.]
 [5. 1. 9. 2. 6. 4. 7. 3. 8.]
 [4. 9. 1. 3. 5. 2. 8. 7. 6.]
 [3. 2. 6. 9. 7. 8. 5. 1. 4.]
 [7. 8. 5. 1. 4. 6. 3. 9. 2.]]
Is the solution correct?
True

This is sudoku number 17
[[0. 7. 0. 0. 6. 0. 0. 0. 5.]
 [9. 0. 0. 2. 1. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 0. 6. 0. 4.]
 [2. 0. 0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 6. 0. 0. 8.]
 [0. 1. 0. 7. 0. 9. 0. 5. 0.]
 [0. 0. 4. 0. 5. 0. 2. 0. 0.]
 [1. 0. 7. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]]
The solution for sudoku number 17
[[4. 7. 1. 8. 6. 3. 9. 2. 5.]
 [9. 5. 6. 2. 1. 4. 8. 3. 7.]
 [8. 2. 3. 9. 7. 5. 6. 1. 4.]
 [2. 4. 9. 5. 3. 8. 1. 7. 6.]
 [7. 3. 5. 1. 2. 6. 4. 9. 8.]
 [6. 1. 8. 7. 4. 9. 3. 5. 2.]
 [3. 9. 4. 6. 5. 7. 2. 8. 1.]
 [1. 6. 7. 3. 8. 2. 5. 4. 9.]
 [5. 8. 2. 4. 9. 1. 7. 6. 3.]]
Is the solution correct?
True

This is sudoku number 18
[[0. 0.